services:
  postgres:
   container_name: backend_db
   restart: always
   image: postgres:17
   environment:
     POSTGRES_DB: 'budget_app_db'
     POSTGRES_USER: 'main-system'
     POSTGRES_PASSWORD: '5555'
   volumes:
     - ./database/seed_data:/seed/
     - ./database/schemas:/schemas/
     - ./database/pg_vol:/var/lib/postgresql/data/
   ports:
    - 5432:5432